### PR TITLE
fix: fix wrong library dependency

### PR DESCRIPTION
**Pull request by graykode**
Sir some dependencies in your cargo.toml are wrong (you've closed github repos)
here is some right cargo.tml

### CODE REVIEW

**Comment by graykode** [comment]
Also I moved https://github.com/0xpapercut/substreams-solana-utils to utils folder

**Comment by 0xpapercut** [comment]
Indeed, thank you very much. Just one detail: I would like for substreams-solana-utils to remain in its own repo (I'll cherry pick so you don't have to do anything else)

**Comment by 0xpapercut** [comment]
If you have any other suggestions, let me know :)

**Comment by graykode** [comment]
@0xpapercut Yep! thanks for your great project 🫡

**Pull request closed without merging**
